#!/usr/bin/env bash
# Install haproxy
FOO="\
frontend load_balancer
    bind *:80
    mode http
    default_backend foo
    
backend foo
    balance roundrobin
    server 1846-web-01 34.75.175.204:80 check
    server 1846-web-02 35.196.107.55:80 check
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$FOO" >> /etc/haproxy/haproxy.cfg
service haproxy start
